version: '3.5'
services:
  container:
    build:
      context: ./
      dockerfile: dockerfiles/svn_commit_notifier/Dockerfile
    command: ['sh', 'dockerfiles/svn_commit_notifier/init.sh']
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/usr/local/src
    working_dir: /usr/local/src
